ignore:
  - "Com.DanLiris.Service.Purchasing.Lib/Migrations" 
  - "Com.DanLiris.Service.Purchasing.Lib/AutoMapperProfiles" 
  - "Com.DanLiris.Service.Purchasing.Lib/Serializers" 
  - "Com.DanLiris.Service.Purchasing.Lib/Services" 
  - "Com.DanLiris.Service.Purchasing.Lib/Facades/BudgetCashflowService" 
  - "Com.DanLiris.Service.Purchasing.Lib/Facades/DebtAndDispositionSummary" 
  - "Com.DanLiris.Service.Purchasing.Lib/Facades/DebtAndDispositionSummary" 
  - "Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentPurchasingExpedition" 
  - "Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentBeaCukaiFacade" 
  - "Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDailyPurchasingReportFacades" 
  - "Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDispositionPurchaseFacades" 
  - "Com.DanLiris.Service.Purchasing.Lib/MongoDbContext.cs" 
  - "Com.DanLiris.Service.Purchasing.WebApi/Startup.cs"
  - "Com.DanLiris.Service.Purchasing.WebApi/Program.cs"
  - "Com.DanLiris.Service.Purchasing.WebApi/Tools"
  - "Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/ExternalPurchaseOrderControllers"
  - "Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/InternalPurchaseOrderControllers"
  - "Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/PurchaseRequestControllers"
  - "Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/BudgetCashflowController.cs"
  - "Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentBeaCukaiControllers"
  - "Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentInvoiceControllers"
  - "Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentPurchasingExpeditionController.cs"
  - "Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/UnpaidDispositionReport"
  - "Com.DanLiris.Service.Purchasing.WebApi/SchedulerJobs/MasterRegistry.cs"